### ISSUE TITLE
Bar chart doesn't seem to cope gracefully with empty dataset

### ISSUE THREAD

**Issue by mockdeep** [mattetti/googlecharts#72]
When I have an empty data set, I get an error from google charts:

```
 > Gchart.bar(:data => [[],[],[]])
NoMethodError: undefined method `-' for nil:NilClass
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:594:in `block in encode_scaled_dataset'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:592:in `each'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:592:in `encode_scaled_dataset'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:624:in `simple_encoding'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:328:in `set_data'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:659:in `block in query_builder'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:656:in `map'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:656:in `query_builder'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:652:in `url_builder'
    from /home/fletch/.rvm/gems/ruby-2.1.2/gems/googlecharts-1.6.8/lib/gchart.rb:299:in `url'
    from (eval):12:in `bar'
    from (irb):3
```

**Comment by Seven0711** [comment]
请问使用Google chart要引入哪些文件，去哪里下载？
